import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>kidme</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/social.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://islands.xyz/@kidme/gallery">kidme.eth 🏝</a>
        </h1>

        <h1 className={styles.description}>Hello my name is David a Fullstack Web Developer</h1>
        <div className={styles.grid}>
          <a href="https://mirror.xyz/kidme.eth" className={styles.card}>
            <h2>Writings &rarr;</h2>
            <p>Writings hosted on mirror.xyz</p>
          </a>

          <a href="https://twitter.com/SAINt_KIDME" className={styles.card}>
            <h2>My Twitter &rarr;</h2>
            <p>Please feel free to follow me on social</p>
          </a>

          <a href="https://github.com/dfimbres" className={styles.card}>
            <h2>Work &rarr;</h2>
            <p>My Github Profile</p>
          </a>
          
          <a href="https://rainbow.me/kidme.eth" className={styles.card}>
            <h2>Wallet &rarr;</h2>
            <p>Showing off my collection 🌈</p>
          </a>
        </div>
      </main>
    </div>
  )
}
